# Generated by Django 4.2.1 on 2023-05-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_new',
            name='Date',
        ),
    ]
