# Generated by Django 4.2.1 on 2023-05-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_new_nationalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_new1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auther', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Context', models.TextField()),
                ('Nationalcode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='blog_new',
        ),
    ]
