# Generated by Django 4.2.1 on 2023-05-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey_u',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Drname', models.CharField(max_length=200)),
            ],
        ),
    ]
